[package]
name = "test-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.18", features = ["json"] }
tokio = {version="1.45.1", features=["full"]}
windows = "0.61.1"
winreg = "0.55.0"
