[package]
name = "rust_part"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
console = "0.15.8"
dialoguer = "0.11.0"
dirs = "5.0.1"
indexmap = "2.2.6"
log = "0.4.22"
rand = "0.8.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
