[package]
name = "rust_part"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
dialoguer = "0.11.0"
rand = "0.8.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
